[tox]
isolated_build = True
skipsdist = 1    # does not generate a package, defaults to false
env_list =
    format


[testenv:format]
description = lint and format code with yapf, isort and flake8
deps =
    toml
    yapf
    isort
    flake8
    Flake8-pyproject

commands =
    yapf .{/}src -irp
    isort .{/}src
    flake8 .{/}src
